/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a40eca27-b0a3-41b9-a471-7d665711baad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hHPvS1EV8",
    "aws_user_pools_web_client_id": "kj8897n6keafg5oslevpar7r9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://d3tffdhimraqbb33nijmbgzq3i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "currencytable-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "facial-db-us-east-1182825-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
